export const FETCH_CHARGER_LOCATIONS_REQUEST = "FETCH_CHARGER_LOCATIONS_REQUEST";
export const FETCH_CHARGER_LOCATIONS_SUCCESS = "FETCH_CHARGER_LOCATIONS_SUCCESS";

export const FETCH_SELECTED_CHARGER_REQUEST = "FETCH_SELECTED_CHARGER_REQUEST";
export const FETCH_SELECTED_CHARGER_SUCCESS = "FETCH_SELECTED_CHARGER_SUCCESS";

export const SET_SHOW_CHARGER_MODAL = "SET_SHOW_CHARGER_MODAL";
